sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jtrolle/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jtrolle/docker-react npm run test